language: rust
rust:
  - stable
install:
  - wget https://github.com/nanomsg/nanomsg/archive/1.0.0.tar.gz
  - tar -xvf 1.0.0.tar.gz
  - cd nanomsg-1.0.0
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo cmake --build . --target install
  - sudo ldconfig
after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/flatlined-*